name: 'Setup Gradle'
description: 'Checks out the repository and sets up Java and Gradle'
inputs:
  token:
    description: 'token input for actions/checkout'
    required: false
    default: ${{ github.token }}
  fetch-depth:
    description: 'fetch-depth input for actions/checkout'
    required: false
    default: 1
  ref:
    description: 'ref input for actions/checkout'
    required: false
  java-version:
    description: 'java-version input for actions/setup-java'
    required: false
    default: 21
  gradle-version:
    description: 'gradle-version input for actions/setup-java'
    required: false
  cache-read-only:
    description: 'cache-read-only input for gradle/actions/setup-gradle'
    required: false
    default: ${{ github.event.repository != null && github.ref_name != github.event.repository.default_branch }}
  dependency-graph:
    description: 'dependency-graph input for gradle/actions/setup-gradle'
    required: false
    default: 'disabled'
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}

    - name: Set up JDK
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4
      with:
        add-job-summary: always
        cache-cleanup: on-success
        cache-read-only: ${{ inputs.cache-read-only }}
        dependency-graph: ${{ inputs.dependency-graph }}
        gradle-version: ${{ inputs.gradle-version }}
        validate-wrappers: true
