on:
  pull_request:
  merge_group:

name: Check pull request

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  check-codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Setup build environment
        uses: buckley-w-david/android-password-store/.github/reusable-workflows/setup-gradle@main

      - name: Check codestyle
        shell: bash
        run: ./gradlew spotlessCheck

      - name: Upload Kotlin build report
        if: "${{ always() }}"
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: Build report (check-codestyle)
          path: build/reports/kotlin-build/

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup build environment
        uses: buckley-w-david/android-password-store/.github/reusable-workflows/setup-gradle@main

      - name: Run unit tests
        shell: bash
        run: ./gradlew test -PslimTests

      - name: (Fail-only) Upload test report
        if: "${{ failure() }}"
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: Test report (unit-tests)
          path: app/build/reports

      - name: Upload Kotlin build report
        if: "${{ always() }}"
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: Build report (unit-tests)
          path: build/reports/kotlin-build/

  build-apks:
    runs-on: ubuntu-latest
    steps:
      - name: Setup build environment
        uses: buckley-w-david/android-password-store/.github/reusable-workflows/setup-gradle@main

      - name: Build debug APKs
        shell: bash
        run: ./gradlew assembleFreeDebug assembleNonFreeDebug assembleNonFreeRelease

      - name: Upload Kotlin build report
        if: "${{ always() }}"
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: Build report (build-apks)
          path: build/reports/kotlin-build/

  check-api:
    runs-on: ubuntu-latest
    steps:
      - name: Setup build environment
        uses: buckley-w-david/android-password-store/.github/reusable-workflows/setup-gradle@main

      - name: Check library API
        shell: bash
        run: ./gradlew metalavaCheckCompatibilityRelease

      - name: Upload Kotlin build report
        if: "${{ always() }}"
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: Build report (check-api)
          path: build/reports/kotlin-build/

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup build environment
        uses: buckley-w-david/android-password-store/.github/reusable-workflows/setup-gradle@main

      - name: Run Lint
        shell: bash
        run: ./gradlew lint

      - name: Upload Kotlin build report
        if: "${{ always() }}"
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: Build report (lint)
          path: build/reports/kotlin-build/
