name: Sync localisations from Crowdin
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  sync-crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Setup build environment
        uses: buckley-w-david/android-password-store/.github/reusable-workflows/setup-gradle@main

      - name: Sync translations to/from Crowdin
        id: crowdin
        uses: crowdin/github-action@2cc7959c565767d6bc118118d6df3b63bf361370 # v2
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          localization_branch_name: l10n_crowdin_translations
          create_pull_request: true
          pull_request_title: 'New Crowdin Translations'
          pull_request_body: 'New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)'
          pull_request_base_branch_name: 'main'
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.PSL_UPDATE_TOKEN }}

      - name: Enable automerge for PR
        shell: bash
        run: |
          gh pr merge --squash --auto "${PR_URL}"
        env:
          GITHUB_TOKEN: ${{ secrets.PSL_UPDATE_TOKEN }}
          PR_URL: ${{ steps.crowdin.outputs.pull-request-url }}
